In [1]:
import os
import pandas as pd

In [2]:
# file paths
home = r'C:\Users\carroll\Documents\sbgPlant'
ref = os.path.join(home, 'schema')
col = os.path.join(home, 'data', 'col_2018')
raw = os.path.join(col, 'raw')
loc = os.path.join(raw, '10.15485.1618130', 'data')

out_folder = os.path.join(col, 'out_csv')

table = 'campaign'

# load schema and dtype
schema = pd.read_csv(os.path.join(ref, 'sbgplants-schema.csv'))
data_types = pd.read_csv(os.path.join(ref, 'data-types.csv'))

In [3]:
# view relevant schema
schema = schema[schema.table_name==table]

# fix typos
schema['column_name'] = schema['column_name'].replace('doy', 'doi')
schema['column_name'] = schema['column_name'].replace('primary_founding_agency', 'primary_funding_agency')
schema

  table_name             column_name     data_type
0   campaign           campaign_name     character
1   campaign  primary_funding_agency     character
2   campaign         data_repository  USER-DEFINED
3   campaign                     doi     character

In [12]:
# view relevant data-types info
# for now we can't do this automatically by column_name, because column_name is not explicitly linked to enum_type in any way yet

data_types = data_types[data_types['Enum Type']=='Repository']
data_types

       Schema   Enum Type Enum Value
22  sbgplants  Repository     ECOSIS
23  sbgplants  Repository       NEON
24  sbgplants  Repository  ORNL DAAC

In [4]:
# load relevant reference raw tables
sample_site = pd.read_csv(os.path.join(loc, 'sample_site.csv'))
sample_site.Campaign.unique()

array(['ER18'], dtype=object)

In [15]:
# prepare & populate out table
out_table = pd.DataFrame(columns=schema['column_name'].unique())

out_table['campaign_name'] = ['East River 2018']
out_table['primary_funding_agency'] = 'DOE'
out_table['data_repository'] = 'ESS-DIVE'
out_table['doi'] = r'10.15485/1618130, 10.15485/1618132, 10.15485/1631278, 10.15485/1617204, 10.15485/1618131' # should this be updated to the CHESS landing page?

out_table

,campaign_name,primary_funding_agency,data_repository,doi
0,East River 2018,DOE,ESS-DIVE,"10.15485/1618130, 10.15485/1618132, 10.15485/1..."

In [16]:
# check data types
out_table.dtypes

campaign_name             object
primary_funding_agency    object
data_repository           object
doi                       object
dtype: object

In [17]:
# export table
fp_out = os.path.join(out_folder, f'{table}.csv')
out_table.to_csv(fp_out, index=False)